### ISSUE TITLE
Cannot compile following the instructions in src/FcEtt/LIBRARIES.md

### ISSUE THREAD

**Issue by jimyu94** [sweirich/corespec#1]
Hi! I am a Coq enthusiast and I would love to try your code, but I've experienced difficulties. I am using Coq 8.7.1 and coq-mathcomp-ssreflect 1.6.4, but I am almost certain that the problems aren't caused by the version difference. I experienced the following problems and errors.

1.  In step 11, after `cd metalib`, `git checkout 8.6` seemed not useful.

2. In step 12, only if I `cd metalib/Metalib` can I `make`, which is different from the instructions.

3. No matter how I put metalib I cannot succeed in `make coq` in the FcEtt folder. I've tried putting metalib along with the src folder, or metalib along with FcEtt, or metalib/Metalib along with FcEtt, or metalib/Metalib inside FcEtt. However, I got different error messages for these tests.

Could you please test if there could be something wrong in your instructions? Thanks!

**Comment by sweirich** [comment]
Hi, Thanks for your issue.  You are right, the instructions had gotten out of date with respect to changes with metalib.  I've updated the instructions to point directly to metalib. Please follow the steps there. (In particular, the instructions tell you to 'make install' so it shouldn't matter where you put metalib.)

**Comment by jimyu94** [comment]
Thanks for helping! You addressed my first two issues perfectly, but I still don't know where I should put `metalib` (or `metalib/Metalib`) in order to compile `src` (my 3rd question). Could you help on this as well? Thank you!

**Comment by sweirich** [comment]
If you do `make install` as part of the metalib installation, it shouldn't matter where you put the directory. (It should be globally managed by opam).  If you still are having trouble, please follow up with your actual error message. Thanks.
